# Change these first
owner: creeperita09 # Your GitHub organization or username, where this repository lives
repo: Tssonor-status # The name of this repository

sites:
  - name: Main Panel
    url: https://panel.tssonor.com
  - name: Client Area
    url: https://shop.tssonor.com
  - name: Tssonor.com
    url: https://tssonor.com
  - name: Main Node
    url: https://ptdl-node1.tssonor.com
  - name: Node 2 (bot host)
    url: https://ptdl-node3.tssonor.com
  
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.tssonor.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Tssonor Status | Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Tssonor status page.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
